# Generated by Django 4.2.6 on 2023-11-01 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('profil_image', models.ImageField(blank=True, default='image.png', null=True, upload_to='images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='1', max_length=50)),
                ('price', models.IntegerField()),
                ('rp', models.CharField(default='0', max_length=100)),
                ('acount_image', models.ImageField(default='defult_img', upload_to='profileimg/')),
                ('turi', models.CharField(choices=[('garant account', 'garant account'), ('reseler account', 'reseler account')], default=None, max_length=20)),
                ('mifik', models.CharField(default='ok', max_length=100)),
                ('qoshimcha', models.CharField(default='qoshimchalar', max_length=100)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profilemodel')),
            ],
        ),
    ]
