# Generated by Django 4.2.6 on 2023-11-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_accountmodel_murojaat_uchun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='murojaat_uchun',
            field=models.CharField(default='+998', max_length=100),
        ),
    ]
